export const filterData = {
  Availability: {
    instock: false,
    outstock: false,
    preorder: false,
  },
  Category: {
    "Sony Mobiles": false,
    CMF_by_Nothing: false,
    NFC_Mobile_Phone_in_Kuwait: false,
    "60_KWD_Mobiles_in_Kuwait": false,
    "Samsung Mobiles": false,
    "Apple iPhones": false,
    "OnePlus Mobiles": false,
    "Nokia Mobiles": false,
    "Xiaomi Mobiles": false,
    "Huawei Mobiles": false,
    "LG Mobiles": false,
    "Google Pixel": false,
    "Oppo Mobiles": false,
    "Realme Mobiles": false,
    "Motorola Mobiles": false,
    "Asus Mobiles": false,
    "Vivo Mobiles": false,
    "Tecno Mobiles": false,
    "Infinix Mobiles": false,
    "Lenovo Mobiles": false, 
    "Honor Mobiles": false, 
  },
  Price: {
    "0-500": false,     
    "500-1000": false,
    "1000-2000": false,
    "2000-3000": false,
    "3000-4000": false,
    "4000-5000": false, 
    "5000-6000": false, 
    "6000-7000": false, 
    "7000-8000": false, 
    "8000-10000": false, 
    "10000+": false, 
  },
  Ram: {
    "2GB": false,
    "4GB": false,
    "6GB": false,
    "8GB": false,
    "12GB": false,
    "16GB": false,
    "18GB": false, 
    "20GB": false, 
    "32GB": false, 
  },
  Storage: {
    "32GB": false,
    "64GB": false,
    "128GB": false,
    "256GB": false,
    "512GB": false,
    "1TB": false, 
    "2TB": false, 
  },
};

export const getFilterFromSearchParams = (searchParams) => {
  return {
    Availability: {
      instock: searchParams.get("instock") === "true",
      outstock: searchParams.get("outstock") === "true",
      preorder: searchParams.get("preorder") === "true", 
    },
    Category: {
      "Sony Mobiles": searchParams.get("Sony Mobiles") === "true",
      CMF_by_Nothing: searchParams.get("CMF_by_Nothing") === "true",
      NFC_Mobile_Phone_in_Kuwait: searchParams.get("NFC_Mobile_Phone_in_Kuwait") === "true",
      "60_KWD_Mobiles_in_Kuwait": searchParams.get("60_KWD_Mobiles_in_Kuwait") === "true",
      "Samsung Mobiles": searchParams.get("Samsung Mobiles") === "true",
      "Apple iPhones": searchParams.get("Apple iPhones") === "true",
      "OnePlus Mobiles": searchParams.get("OnePlus Mobiles") === "true",
      "Nokia Mobiles": searchParams.get("Nokia Mobiles") === "true",
      "Xiaomi Mobiles": searchParams.get("Xiaomi Mobiles") === "true", 
      "Huawei Mobiles": searchParams.get("Huawei Mobiles") === "true", 
      "LG Mobiles": searchParams.get("LG Mobiles") === "true", 
      "Google Pixel": searchParams.get("Google Pixel") === "true", 
      "Oppo Mobiles": searchParams.get("Oppo Mobiles") === "true", 
      "Realme Mobiles": searchParams.get("Realme Mobiles") === "true", 
      "Motorola Mobiles": searchParams.get("Motorola Mobiles") === "true", 
      "Asus Mobiles": searchParams.get("Asus Mobiles") === "true", 
      "Vivo Mobiles": searchParams.get("Vivo Mobiles") === "true", 
      "Tecno Mobiles": searchParams.get("Tecno Mobiles") === "true", 
      "Infinix Mobiles": searchParams.get("Infinix Mobiles") === "true", 
      "Lenovo Mobiles": searchParams.get("Lenovo Mobiles") === "true", 
      "Honor Mobiles": searchParams.get("Honor Mobiles") === "true", 
    },
    Price: {
      "0-500": searchParams.get("0-500") === "true",
      "500-1000": searchParams.get("500-1000") === "true",
      "1000-2000": searchParams.get("1000-2000") === "true",
      "2000-3000": searchParams.get("2000-3000") === "true",
      "3000-4000": searchParams.get("3000-4000") === "true",
      "4000-5000": searchParams.get("4000-5000") === "true", 
      "5000-6000": searchParams.get("5000-6000") === "true", 
      "6000-7000": searchParams.get("6000-7000") === "true", 
      "7000-8000": searchParams.get("7000-8000") === "true", 
      "8000-10000": searchParams.get("8000-10000") === "true", 
      "10000+": searchParams.get("10000+") === "true", 
    },
    Ram: {
      "2GB": searchParams.get("2GB") === "true",
      "4GB": searchParams.get("4GB") === "true",
      "6GB": searchParams.get("6GB") === "true",
      "8GB": searchParams.get("8GB") === "true",
      "12GB": searchParams.get("12GB") === "true",
      "16GB": searchParams.get("16GB") === "true",
      "18GB": searchParams.get("18GB") === "true", 
      "20GB": searchParams.get("20GB") === "true", 
      "32GB": searchParams.get("32GB") === "true", 
    },
    Storage: {
      "32GB": searchParams.get("32GB") === "true",
      "64GB": searchParams.get("64GB") === "true",
      "128GB": searchParams.get("128GB") === "true",
      "256GB": searchParams.get("256GB") === "true",
      "512GB": searchParams.get("512GB") === "true",
      "1TB": searchParams.get("1TB") === "true", 
      "2TB": searchParams.get("2TB") === "true", 
    },
  };
};
